services:
  # --- 1. Neo4j ---
  neo4j:
    image: neo4j:5.12.0
    container_name: mon-neo4j
    hostname: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/projet1234
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j-data:/data
    networks:
      - graph-network

  # --- 2. Spark Master ---
  spark-master:
    image: apache/spark:3.5.3
    container_name: mon-spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    networks:
      - graph-network

  # --- 3. Spark Worker ---
  spark-worker:
    image: apache/spark:3.5.3
    container_name: mon-spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - graph-network

  # --- 4. Zeppelin ---
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: mon-zeppelin
    ports:
      - "8082:8080"
    volumes:
      - ./zeppelin-notebooks:/opt/zeppelin/notebook
      - ./data:/data
    environment:
      - ZEPPELIN_ADDR=0.0.0.0
      - SPARK_HOME=/opt/spark
      - MASTER=spark://mon-spark-master:7077
    depends_on:
      - spark-master
    networks:
      - graph-network

# DÃ©claration des volumes persistants
volumes:
  neo4j-data:
  hadoop-data:

networks:
  graph-network:
    driver: bridge
